### ISSUE TITLE
Customization to turn on this mode permanently

### ISSUE THREAD

**Issue by jglick** [Vifon/focus-autosave-mode.el#4]
It is fine for this package to be opt-in but do I really need to edit my `~/.emacs` to run

```lisp
(focus-autosave-mode)
```

? And then I get the `focus-save` annotation in every modeline, which just wastes space.

It would be more usable to be able to `M-x customize` and just have this mode be on all the time, without affecting modeline display.

**Comment by vifon** [comment]
Did you consider using [diminish](https://github.com/myrjola/diminish.el)? I don't remember any mode that would hide its mode line lighter on its own.

**Comment by jglick** [comment]
Maybe I should rephrase: my expectation for a package like this is that it would not have to be a “mode” per se, just a global behavior of Emacs that can be switched on.

**Comment by vifon** [comment]
> (...) a global behavior of Emacs that can be switched on.

That's more or less exactly what a mode is. I don't think it'd be a good idea to implement it in such way when we have alternatives like `diminish`. I'm closing it for now, but if I missed some disadvantage of such an approach, feel free to continue the discussion.
